#!/usr/bin/env python

import os

Import('env')

env['CC'] = 'clang'
env['CFLAGS'] = Split('-std=c11 -g -fcolor-diagnostics')
env['CPPPATH'] = '#/src/godot-cpp/include'

so = env.SharedLibrary('libgdpoolbytearrayext.so', ['poolbytearray_ext.cpp'])
inst_so = env.Install('#addons/gdpoolbytearrayext', '#build/linux/libpoolbytearrayext.so')
env.Depends(inst_so, so)
